create table
  public."Tutorial" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    image text not null default ''::text,
    title text not null,
    views bigint not null default '0'::bigint,
    published text not null,
    constraint Tutorial_pkey primary key (id)
  ) tablespace pg_default;